@ServerURL = http://localhost:3000/api

@token = {{login.response.body.token}}

@categoryID = {{category.response.body.0.id}}

### Login (for token)
# @name login
POST {{ServerURL}}/users/login
Content-Type: application/json

{
    "email": "jani@gmail.com",
    "password": "Titkosjelszo123"
}

### Get categories
# @name category
GET  {{ServerURL}}/category
Content-Type: application/json
Authorization: Bearer {{token}}

### Create category
POST {{ServerURL}}/category/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Bútor"
}

### Modify category
PATCH {{ServerURL}}/category/{{categoryID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Gépjármű"
}

### Delete category
DELETE {{ServerURL}}/category/{{categoryID}}
Content-Type: application/json
Authorization: Bearer {{token}}